### ISSUE TITLE
how to use cookie and session?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [s1n4/leptus#49]
hi，i like this library, it looks very easy to use, but there are some questions:
```
1, how to use cookie?
2, how to use session?
```
is there any sample? Can i just use cowboy cookie and cowboy session instead?

**Comment by s1n4** [comment]
Hello,

I didn't add such functions to `leptus_req` module, because REST APIs are not supposed use Cookies.
But you can use `leptus_req:get_req/1` (https://github.com/s1n4/leptus/blob/master/docs/leptus_req.org#get_req1) to get the Cowboy `Req` object in order to use `cowboy_req` module. After you're done with `cowboy_req`, set the new `Req` (that would be returned by `cowboy_req`) using `leptus_req:set_req/2`.

**Comment by ziyouchutuwenwu** [comment]
ok, thank you very much.
